invoices/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('sign-up/', views.signup_view, name='sign_up'),
    path('<int:pk>/delete/', views.UserDeleteView.as_view(), name='user_delete'),
    path('profile/create/', views.ProfileCreate.as_view(), name='cprofile'),
    path('cprofile/', views.CompanyProfileDetail.as_view(), name='company_profile'),
    path('iprofile/', views.IndividualProfileDetail.as_view(), name='individual_profile'),
    path('cprofile/update/', views.CompanyProfileUpdate.as_view(), name='cprofile_update'),
    path('iprofile/update/', views.IndividualProfileUpdate.as_view(), name='iprofile_update'),
    path('profile/bank/', views.BankAccountUpdateView.as_view(), name='bank'),
]

invoices/billing/urls.py
from django.urls import path
from . import views

app_name = 'billing'

urlpatterns = [
    path('buyer/<int:pk>/', views.UpdateBuyer.as_view(), name='update_buyer'),
    path('buyer/list/', views.ListBuyers.as_view(), name='list_buyers'),
    path('buyer/add/', views.CreateBuyer.as_view(), name='add_buyer'),
    path('buyer/<int:pk>/delete/', views.DeleteBuyer.as_view(), name='delete_buyer'),
    path('invoice/list/', views.ListInvoices.as_view(), name="list_invoices"),
    path('invoice/<int:pk>/', views.DetailInvoice.as_view(), name='detail_invoice'),
    path('invoice/create/', views.CreateInvoice.as_view(), name='create_invoice'),
    path('invoice/<int:pk>/update/', views.UpdateInvoice.as_view(), name='update_invoice'),
    path('invoice/<int:pk>/delete/', views.DeleteInvoice.as_view(), name='delete_invoice'),
    path('invoice/<int:pk>/createitem/', views.CreateInvoiceItem.as_view(), name='create_item'),
    path('invoice/item/<int:pk>/update/', views.UpdateInvoiceItem.as_view(), name='update_item'),
    path('invoice/item/<int:pk>/delete/', views.DeleteInvoiceItem.as_view(), name='delete_item'),
    path('invoice/<int:invoice_id>/pdf/', views.generate_invoice_pdf, name='invoice_pdf'),
]

invoices/core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('example/', views.Example.as_view(), name='example'),
]

invoices/invoices/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

reg_urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

]

urlpatterns = [
    path('admin-panel/', admin.site.urls),
    path('', include('core.urls')),
    path('accounts/', include('accounts.urls')),
    path('billing/', include('billing.urls')),
] + reg_urlpatterns

invoices/templates/includes/footer.html
<div class="foot container-fluid frosty fixed-bottom">
    <p class="text-center my-2">Contact me at <a href="mailto:suppert@billmaker.eu">support@billmaker.eu</a> or <a href="https://www.linkedin.com/in/tadas-joneliukstis">LinkedIn</a></p>
</div>

invoices/templates/includes/navbar.html
<nav class="navbar navbar-dark navbar-expand-lg fixed-top frosty">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'core:index' %}">Home</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li>
          <a class="nav-link" href="{% url 'core:example' %}">Example</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'billing:list_invoices' %}">Invoices</a>
        </li>
        
        <li class="nav-item">
          <a class="nav-link" href="{% url 'billing:list_buyers' %}">Clients</a>
        </li>
        {% endif %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            {% if user.is_authenticated %}
            User panel
            {% else %}
            Account
            {% endif %}
          </a>
          <ul class="dropdown-menu">
            {% if user.is_authenticated %}
                {% if user.is_company %}
                <li><a class="dropdown-item" href="{% url 'accounts:company_profile' %}">Company profile</a></li>
                 {% else %}
                <li><a class="dropdown-item" href="{% url 'accounts:individual_profile' %}">Profile</a></li>
                {% endif %}
                <form method="POST" action="{% url 'logout' %}">
                {% csrf_token %}
                    <button type="submit" class="dropdown-item">Logout</button>
                </form>
            {% else %}
            <li><a class="dropdown-item" href="{% url 'login' %}">Log In</a></li>
            <li><a class="dropdown-item" href="{% url 'accounts:sign_up' %}">Sign Up</a></li>
            {% endif %}
          </ul>
        </li>
      </ul>
      {% if user.is_authenticated %}<span class="text-info ms-auto">Logged in as: {{ user.email }}</span>{% endif %}
    </div>
  </div>
</nav>