invoices/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('sign-up/', views.signup_view, name='sign_up'),
    path('<int:pk>/delete/', views.UserDeleteView.as_view(), name='user_delete'),
    path('profile/create/', views.ProfileCreate.as_view(), name='cprofile'),
    path('cprofile/', views.CompanyProfileDetail.as_view(), name='company_profile'),
    path('iprofile/', views.IndividualProfileDetail.as_view(), name='individual_profile'),
    path('cprofile/update/', views.CompanyProfileUpdate.as_view(), name='cprofile_update'),
    path('iprofile/update/', views.IndividualProfileUpdate.as_view(), name='iprofile_update'),
    path('profile/bank/', views.BankAccountUpdateView.as_view(), name='bank'),
]

invoices/core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('example/', views.Example.as_view(), name='example'),
]

invoices/invoices/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

reg_urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

]

urlpatterns = [
    path('admin-panel/', admin.site.urls),
    path('', include('core.urls')),
    path('accounts/', include('accounts.urls')),
    path('billing/', include('billing.urls')),
] + reg_urlpatterns

invoices/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
# Create your models here.

class UserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError("Users must have an email!")
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields) #login with email
        user.set_password(password)
        user.save(using=self._db)
        return user
    
    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self.create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True)
    is_company = models.BooleanField(verbose_name='Are you a company or individual?', default=False) #True = company, False = individual
    is_staff = models.BooleanField(default=False) #allows login on admin site
    is_active = models.BooleanField(default=True) #allows soft ban without delete user
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = UserManager()

    def __str__(self):
        return self.email
    
    @property
    def profile(self):
        if hasattr(self, 'individual_profile'):
            return self.individual_profile
        elif hasattr(self, 'company_profile'):
            return self.company_profile
        return None


class BaseProfile(models.Model):
    address = models.CharField(max_length=100)
    phone = models.CharField(verbose_name='Contact phone', max_length=15, null=True, blank=True)
    email = models.EmailField(verbose_name='Contact email', null=True, blank=True)
    web = models.CharField(verbose_name='Web site', max_length=100, null=True, blank=True)

    class Meta:
        abstract = True  #don't create separate db table for this. CompanyProfile and IndividualProfile will include fields of this class


class CompanyProfile(BaseProfile):  
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="company_profile")
    name = models.CharField(verbose_name='Company name', max_length=200)
    company_code = models.CharField(verbose_name='Company code', max_length=20)
    vat_code = models.CharField(verbose_name='Tax payer code', max_length=20)

    def __str__(self):
        return self.name


class IndividualProfile(BaseProfile):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='individual_profile')
    name = models.CharField(verbose_name='Full name', max_length=100)
    individual_code = models.CharField('Individual code', max_length=20, null=True, blank=True)
    vat_code = models.CharField(verbose_name='Tax payer code', max_length=20, null=True, blank=True)

    def __str__(self):
        return self.name


class BankAccount(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='bank')
    bank_name = models.CharField(verbose_name='Bank name', max_length=20, null=True, blank=True)
    swift = models.CharField(verbose_name='Bank code (SWIFT)', max_length=10, null=True, blank=True)
    iban = models.CharField(verbose_name='iban', max_length=20)

    def __str__(self):
        return f"Bank account for user: {self.user.email}"

invoices/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import User, CompanyProfile, IndividualProfile, BankAccount

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['email', 'is_company']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['is_company'].widget = forms.RadioSelect(choices=[
            (True, 'Company'),
            (False, 'Individual'),
        ])

class CompanyProfileForm(forms.ModelForm):
    class Meta:
        model = CompanyProfile
        fields = ['name', 'company_code', 'email', 'phone', 'web', 'address', 'vat_code']
        exclude = ['user']

class IndividualProfileForm(forms.ModelForm):
    class Meta:
        model = IndividualProfile
        fields = ['name', 'individual_code', 'email', 'phone', 'web', 'address', 'vat_code']
        exclude = ['user']

class BankAccountForm(forms.ModelForm):
    class Meta:
        model = BankAccount
        fields = ['iban', 'bank_name', 'swift']

invoices/accounts/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth import login
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import DetailView, CreateView, UpdateView, DeleteView
from .forms import CustomUserCreationForm, CompanyProfileForm, IndividualProfileForm, BankAccountForm
from .models import CompanyProfile, IndividualProfile, BankAccount, User

# Create your views here.

def signup_view(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user, backend='django.contrib.auth.backends.ModelBackend')    
            return redirect('accounts:cprofile')
    else:
        form = CustomUserCreationForm()
    return render(request, 'registration/register.html', {'form': form})


class ProfileCreate(LoginRequiredMixin, CreateView):
    template_name = "accounts/cprofile.html"

    def get_form_class(self):
        return CompanyProfileForm if self.request.user.is_company else IndividualProfileForm

    def get(self, request, *args, **kwargs):
        profile_form = self.get_form_class()()
        bank_form = BankAccountForm()
        return render(request, self.template_name, {
            'profile_form': profile_form,
            'bank_form': bank_form
        })
    
    def post(self, request, *args, **kwargs):
        profile_form = self.get_form_class()(request.POST)
        bank_form = BankAccountForm(request.POST)
        if profile_form.is_valid() and bank_form.is_valid():
            profile = profile_form.save(commit=False)
            profile.user = request.user
            profile.save()

            bank_account = bank_form.save(commit=False)
            bank_account.user = request.user
            bank_account.save()

            return redirect(self.get_success_url())
        return render(request, self.template_name, {
            'profile_form': profile_form,
            'bank_form': bank_form
        })


    def get_success_url(self):
        if self.request.user.is_company:
            return reverse('accounts:company_profile')
        else:
            return reverse('accounts:individual_profile')


class CompanyProfileDetail(LoginRequiredMixin, DetailView):
    model = CompanyProfile

    def get(self, request, *args, **kwargs):
        try:
            self.object=self.get_object()
        except CompanyProfile.DoesNotExist:
            return redirect(reverse('accounts:cprofile'))
        context = self.get_context_data(object=self.object)
        return self.render_to_response(context)

    def get_object(self):
        return CompanyProfile.objects.get(user=self.request.user)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['fields'] = [
            (field.verbose_name, 
             field.value_from_object(self.object) if field.value_from_object(self.object) is not None else "—")
            for field in self.object._meta.fields
            if field.name not in ['user', 'id']
        ]
        try:
            context['bank_account'] = BankAccount.objects.get(user=self.request.user)
        except BankAccount.DoesNotExist:
            context['bank_account'] = None
        return context
    
    
class IndividualProfileDetail(LoginRequiredMixin, DetailView):
    model = IndividualProfile

    def get(self, request, *args, **kwargs):
        try:
            self.object=self.get_object()
        except IndividualProfile.DoesNotExist:
            return redirect(reverse('accounts:cprofile'))
        context =self.get_context_data(object=self.object)
        return self.render_to_response(context)

    def get_object(self):
        return IndividualProfile.objects.get(user=self.request.user)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['fields'] = [
            (field.verbose_name, 
             field.value_from_object(self.object) if field.value_from_object(self.object) is not None else "—")
            for field in self.object._meta.fields
            if field.name not in ['user', 'id']
        ]
        try:
            context['bank_account'] = BankAccount.objects.get(user=self.request.user)
        except BankAccount.DoesNotExist:
            context['bank_account'] = None
        return context
    

class CompanyProfileUpdate(LoginRequiredMixin, UpdateView):
    model = CompanyProfile
    form_class = CompanyProfileForm
    success_url = "/accounts/cprofile"

    def get_object(self):
        return CompanyProfile.objects.get(user=self.request.user)


class IndividualProfileUpdate(LoginRequiredMixin, UpdateView):
    model = IndividualProfile
    form_class = IndividualProfileForm
    success_url = "/accounts/iprofile"

    def get_object(self):
        return IndividualProfile.objects.get(user=self.request.user)
    

class BankAccountUpdateView(LoginRequiredMixin, UpdateView):
    model = BankAccount
    form_class = BankAccountForm

    def get_object(self):
        return BankAccount.objects.get(user=self.request.user)

    def get_success_url(self):
        return reverse('accounts:company_profile') if self.request.user.is_company else reverse('accounts:individual_profile')


class UserDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = User
    success_url = '/'

    def test_func(self):
        return self.get_object() == self.request.user
    
    def post(self, request, *args, **kwargs):
        if request.POST.get('confirm_text') != 'DELETE':
            return self.get(request, *args, **kwargs)
        return super().post(request, *args, **kwargs)

invoices/accounts/templates/accounts/bankaccount_form.html
{% extends 'base.html' %}
{% block title %}Bank account info{% endblock %}

{% block content %}
{% load crispy_forms_tags %}
<div class="align-items-center justify-content-center flex">
    <div class="text-start frosty-container mx-auto my-3">
        <h3>Bank account info</h3>
        <form method='post'>
        {% csrf_token %}
        {{ form|crispy }}
        <button type='submit' class='btn btn-outline-info'>Confirm</button>
        </form>
    </div>
</div>
{% endblock %}

invoices/accounts/templates/accounts/companyprofile_detail.html
{% extends 'base.html' %}
{% block title %}Company profile{% endblock %}
{% block content %}
<div class="align-items-center justify-content-center flex">
    <div class="text-start frosty-container mx-auto my-3">
        <a href="{% url 'accounts:cprofile_update' %}" class="btn btn-outline-info mb-3">Update profile</a>
        <a href="{% url 'accounts:bank' %}" class="btn btn-outline-info mb-3">Update bank account</a>
        <h3 class="my-3">{{ object.name}} profile</h3> 
        <ul>
        {% for label, value in fields %}
            <li><strong>{{ label|capfirst }}</strong>: {{ value }} </li>
        {% endfor %}
            </ul>
            <h4>Bank Account info:</h4>
            <p><strong>IBAN:</strong> {{ bank_account.iban }}</p>
            <p><strong>Bank Name:</strong> {{ bank_account.bank_name }}</p>
            <p><strong>SWIFT:</strong> {{ bank_account.swift }}</p>
    </div>
</div>
{% endblock %}

invoices/accounts/templates/accounts/companyprofile_form.html
{% extends 'base.html' %}
{% block title%}Update Profile{% endblock %}

{% block content %}
{% load crispy_forms_tags %}

<div class="align-items-center justify-content-center flex">
    <div class="text-start frosty-container mx-auto my-5">
        <h2>Update profile form</h2>
        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-outline-info">Update</button>
            <a href="{% url "accounts:user_delete" object.user.pk %}" class="btn btn-danger">DELETE Account</a>
        </form>
    </div>
</div>

{% endblock %}

invoices/accounts/templates/accounts/cprofile.html
{% extends 'base.html' %}
{% block title%}Create Profile{% endblock %}

{% block content %}
{% load crispy_forms_tags %}
<div class="align-items-center justify-content-center flex">
    <div class="text-start frosty-container mx-auto my-5">
        <h2>Create profile</h2>
        <form method="post">
            {% csrf_token %}
            {{ profile_form|crispy }}
            {{ bank_form|crispy }}
            <button type="submit" class="btn btn-outline-info">Create</button>
            <a href="{% url "accounts:user_delete" user.pk %}" class="btn btn-danger">DELETE Account</a>
        </form>
    </div>
</div>

{% endblock %}

invoices/accounts/templates/accounts/individualprofile_detail.html
{% extends 'base.html' %}
{% block title %}Individual profile{% endblock %}
{% block content %}

<div class="align-items-center justify-content-center flex">
    <div class="text-start frosty-container mx-auto my-3">
        <a href="{% url 'accounts:iprofile_update' %}" class="btn btn-outline-info mb-3">Update profile</a>
        <a href="{% url 'accounts:bank' %}" class="btn btn-outline-info mb-3">Update bank account</a>
        <h3 class="my-3">Individual profile</h3> 
        <ul>
        {% for label, value in fields %}
            <li><strong>{{ label|capfirst }}</strong>: {{ value }} </li>
        {% endfor %}
        </ul>
        <h4>Bank Account info:</h4>
        <p><strong>IBAN:</strong> {{ bank_account.iban }}</p>
        <p><strong>Bank Name:</strong> {{ bank_account.bank_name }}</p>
        <p><strong>SWIFT:</strong> {{ bank_account.swift }}</p>
    </div>
</div>
{% endblock %}

invoices/accounts/templates/accounts/individualprofile_form.html
{% extends 'base.html' %}
{% block title%}Update Profile{% endblock %}

{% block content %}
{% load crispy_forms_tags %}
<div class="align-items-center justify-content-center flex">
    <div class="text-start frosty-container mx-auto my-5">
        <h2>Update profile</h2>
        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-outline-info">Update</button>
            <a href="{% url "accounts:user_delete" object.user.pk %}" class="btn btn-danger">DELETE Account</a>
        </form>
    </div>
</div>

{% endblock %}

invoices/accounts/templates/accounts/user_confirm_delete.html
{% extends 'base.html' %}
{% block title %}DELETE Account{% endblock %}
{% block content %}
<div class="d-flex justify-content-center">
    <div class="frosty-container">
        <h3>DELETE {{ user.email }} Account?</h3>

        <form method="post" action="{% url 'accounts:user_delete' user.pk %}">
            {% csrf_token %}
            <p>This action is permanent and will delete your account along with all associated data including invoices!</p>
            <p>Please make sure you downloaded all the invoices before deleting them together with your account.</p>
            <label>Type "<strong>DELETE</strong>" to confirm:</label>
            <input type="text" name="confirm_text" class="form-control mb-3" required>
            <button type="submit" class="btn btn-danger">Permanently DELETE Account</button>
            {% if object.is_company %}
            <a href="{% url 'accounts:company_profile' %}" class="btn btn-outline-info">Go Back</a>
            {% else %}
            <a href="{% url 'accounts:individual_profile' %}" class="btn btn-outline-info">Go Back</a>
            {% endif %}
        </form>
    </div>
</div>

{% endblock %}