invoices/billing/urls.py
from django.urls import path
from . import views

app_name = 'billing'

urlpatterns = [
    path('buyer/<int:pk>/', views.UpdateBuyer.as_view(), name='update_buyer'),
    path('buyer/list/', views.ListBuyers.as_view(), name='list_buyers'),
    path('buyer/add/', views.CreateBuyer.as_view(), name='add_buyer'),
    path('buyer/<int:pk>/delete/', views.DeleteBuyer.as_view(), name='delete_buyer'),
    path('invoice/list/', views.ListInvoices.as_view(), name="list_invoices"),
    path('invoice/<int:pk>/', views.DetailInvoice.as_view(), name='detail_invoice'),
    path('invoice/create/', views.CreateInvoice.as_view(), name='create_invoice'),
    path('invoice/<int:pk>/update/', views.UpdateInvoice.as_view(), name='update_invoice'),
    path('invoice/<int:pk>/delete/', views.DeleteInvoice.as_view(), name='delete_invoice'),
    path('invoice/<int:pk>/createitem/', views.CreateInvoiceItem.as_view(), name='create_item'),
    path('invoice/item/<int:pk>/update/', views.UpdateInvoiceItem.as_view(), name='update_item'),
    path('invoice/item/<int:pk>/delete/', views.DeleteInvoiceItem.as_view(), name='delete_item'),
    path('invoice/<int:invoice_id>/pdf/', views.generate_invoice_pdf, name='invoice_pdf'),
]

invoices/core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('example/', views.Example.as_view(), name='example'),
]

invoices/invoices/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

reg_urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

]

urlpatterns = [
    path('admin-panel/', admin.site.urls),
    path('', include('core.urls')),
    path('accounts/', include('accounts.urls')),
    path('billing/', include('billing.urls')),
] + reg_urlpatterns

invoices/billing/models.py
from django.db import models
from django.conf import settings
from datetime import date
from decimal import Decimal, ROUND_HALF_UP


# Create your models here.

class Buyer(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    name = models.CharField(verbose_name="Buyer name", max_length=200)
    code = models.CharField(verbose_name="Buyer code", max_length=20)
    vat_code = models.CharField(verbose_name="Buyer tax payer code", max_length=20, null=True, blank=True)
    address = models.CharField(verbose_name="Buyer address", max_length=200, null=True, blank=True)

    def __str__(self):
        return f"Buyer: { self.name }"

class Invoice(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    buyer = models.ForeignKey(Buyer, verbose_name="Buyer", on_delete=models.SET_NULL, null=True, blank=True)
    number = models.IntegerField(verbose_name="Invoice number")
    series = models.CharField(verbose_name="Series", max_length=20)
    issue_date = models.DateField(verbose_name="Issue date", default=date.today)
    due_date = models.DateField(verbose_name="Due date", null=True, blank=True)
    include_vat = models.BooleanField(verbose_name="VAT included", default=True)

    def __str__(self):
        return f"Invoice NO: { self.number } - Buyer: { self.buyer }"
    
    def subtotal(self):
        return sum( item.line_total() for item in self.items.all() )
    
    def vat_amount(self):
        if self.include_vat:
            return self.subtotal() * 21 / Decimal("100.00")
        return Decimal("0.00")

    def total(self):
        total = self.subtotal() + self.vat_amount()
        return total.quantize(Decimal("0.01"), rounding=ROUND_HALF_UP)
    

class InvoiceItem(models.Model):
    invoice = models.ForeignKey(Invoice, related_name="items", on_delete=models.CASCADE)
    description = models.CharField(verbose_name="Description", max_length=255)
    qty = models.DecimalField(verbose_name="Quantity", max_digits=10, decimal_places=2)
    units = models.CharField(verbose_name="Measurement units", max_length=20)
    price = models.DecimalField(verbose_name="Price", max_digits=10, decimal_places=2)
    
    def __str__(self):
        return f"Invoice { self.invoice.number } item: { self.description }: { self.qty } { self.units } x { self.price } Eur"
    
    def line_total(self):
        total = self.qty * self.price
        return total.quantize(Decimal("0.01"), rounding=ROUND_HALF_UP)

invoices/billing/forms.py
from django.forms import ModelForm
from django import forms
from .models import Buyer, Invoice, InvoiceItem


class BuyerForm(ModelForm):
    class Meta:
        model = Buyer
        fields = ['name', 'code', 'vat_code', 'address']


class InvoiceForm(ModelForm):
    class Meta:
        model = Invoice
        fields = ['buyer', 'series', 'number', 'issue_date', 'due_date', 'include_vat']
        widgets = {
            'issue_date': forms.DateInput(attrs={
                'type': 'date',
                'class': 'form-control',
            }),
            'due_date': forms.DateInput(attrs={
                'type': 'date',
                'class': 'form-control',
            }),
            'include_vat': forms.RadioSelect(choices=[
                (True, 'Yes, include VAT'),
                (False, 'No, VAT not applicable'),
            ]),
        }

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        super().__init__(*args, **kwargs)
        self.fields['buyer'].queryset = Buyer.objects.filter(user=user)

class InvoiceItemForm(ModelForm):
    class Meta:
        model = InvoiceItem
        fields = ['description', 'units', 'qty', 'price']

invoices/billing/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, UpdateView, ListView, DeleteView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.template.loader import render_to_string
from django.http import HttpResponse
from weasyprint import HTML
from num2words import num2words

from .forms import BuyerForm, InvoiceForm, InvoiceItemForm
from .models import Buyer, Invoice, InvoiceItem
# Create your views here.

class CreateBuyer(LoginRequiredMixin, CreateView):
    model = Buyer
    form_class = BuyerForm
    success_url = reverse_lazy('billing:list_buyers')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['var'] = 'Add'
        return context


class UpdateBuyer(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Buyer
    form_class = BuyerForm
    success_url = reverse_lazy('billing:list_buyers')

    def get_object(self):
        return Buyer.objects.get(pk=self.kwargs['pk'])
    
    def test_func(self):
        return self.get_object().user == self.request.user
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['var'] = 'Update'
        return context
    

class ListBuyers(LoginRequiredMixin, ListView):
    model = Buyer

    def get_queryset(self):
        return Buyer.objects.filter(user=self.request.user)
    

class DeleteBuyer(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Buyer
    success_url = reverse_lazy('billing:list_buyers')

    def test_func(self):
        return self.get_object().user == self.request.user
    

class CreateInvoice(LoginRequiredMixin, CreateView):
    model = Invoice
    form_class = InvoiceForm
    success_url = reverse_lazy('billing:list_invoices')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)
    
    def get_form_kwargs(self):
         kwargs = super().get_form_kwargs()
         kwargs['user'] = self.request.user
         return kwargs 

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['var'] = 'Create'
        return context
    

class UpdateInvoice(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Invoice
    form_class = InvoiceForm

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)
    
    def get_object(self):
        return Invoice.objects.get(pk=self.kwargs['pk'])

    def test_func(self):
        return self.get_object().user == self.request.user

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['var'] = 'Update'
        return context
    
    def get_success_url(self):
        return reverse_lazy('billing:detail_invoice', kwargs={'pk': self.kwargs['pk']})
    
    def get_form_kwargs(self):
         kwargs = super().get_form_kwargs()
         kwargs['user'] = self.request.user
         return kwargs 

class DetailInvoice(LoginRequiredMixin, UserPassesTestMixin, DetailView):
    model = Invoice

    def get_object(self):
        return get_object_or_404(Invoice, pk=self.kwargs['pk'])

    def test_func(self):
        invoice = self.get_object()
        return invoice.user == self.request.user


class ListInvoices(LoginRequiredMixin, ListView):
    model = Invoice

    def get_queryset(self):
        return Invoice.objects.filter(user=self.request.user)


class DeleteInvoice(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Invoice
    success_url = reverse_lazy('billing:list_invoices')

    def test_func(self):
        return self.get_object().user == self.request.user


class CreateInvoiceItem(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = InvoiceItem
    form_class = InvoiceItemForm

    def get_invoice(self):
        if not hasattr(self, '_invoice'):
            self._invoice = get_object_or_404(Invoice, pk=self.kwargs['pk'])
        return self._invoice

    def form_valid(self, form):
        form.instance.invoice = self.get_invoice()
        return super().form_valid(form)
    
    def test_func(self):
        return self.get_invoice().user == self.request.user

    def get_success_url(self):
        return reverse('billing:detail_invoice', kwargs={'pk': self.kwargs['pk']})
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['var'] = 'Create'
        return context


class UpdateInvoiceItem(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = InvoiceItem
    form_class = InvoiceItemForm

    def get_invoice(self):
        if not hasattr(self, '_invoice'):
            item = get_object_or_404(InvoiceItem, pk=self.kwargs['pk'])
            self._invoice = item.invoice
        return self._invoice

    def test_func(self):
        return self.get_invoice().user == self.request.user

    def get_success_url(self):
        return reverse('billing:detail_invoice', kwargs={'pk': self.get_invoice().pk})
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['var'] = 'Update'
        return context
    

class DeleteInvoiceItem(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = InvoiceItem

    def get_object(self):
        if not hasattr(self, '_object'):
            self._object = get_object_or_404(InvoiceItem, pk=self.kwargs['pk'])
        return self._object
    
    def get_invoice(self):
        return self.get_object().invoice
    
    def test_func(self):
        return self.get_invoice().user == self.request.user
    
    def get_success_url(self):
        return reverse('billing:detail_invoice', kwargs={'pk': self.get_invoice().pk})
    

def generate_invoice_pdf(request, invoice_id):
    from .models import Invoice

    invoice = Invoice.objects.get(pk=invoice_id)
    amount_in_words = num2words(invoice.total(), to='currency', lang='en')
    html_string = render_to_string('billing/pdf_template.html', {'invoice': invoice, 'amount_in_words': amount_in_words})
    html = HTML(string=html_string, base_url=request.build_absolute_uri())
    pdf_file = html.write_pdf()
    response = HttpResponse(pdf_file, content_type='application/pdf')
    response['Content-Disposition'] = f'inline; filename=invoice_{invoice_id}.pdf'
    return response

invoices/billing/templates/billing/buyer_confirm_delete.html
{% extends 'base.html' %}
{% block title %}Delete Buyer{% endblock %}
{% block content %}

<h3 class="my-3">Are you sure you want to delete client: "<strong>{{ object.name }}</strong>" ?</h3>
<form method='post'>
    {% csrf_token %}
    <button type='submit' class='btn btn-danger'>Yes, DELETE</button>
    <a href='{% url "billing:list_buyers" %}' class='btn btn-outline-primary'>Cancel</a>
</form>

{% endblock %}

invoices/billing/templates/billing/buyer_form.html
{% extends 'base.html' %}
{% block title %}{{ var }} Client{% endblock %}
{% block content %}
{% load crispy_forms_tags %}
<div class="align-items-center justify-content-center flex">
    <div class="text-start frosty-container mx-auto my-3">
        <h3>{{ var }} Client </h3>
        <form method='POST'>
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-outline-info">{{ var }} Client</button>
        </form>
    </div>
</div>
{% endblock %}

invoices/billing/templates/billing/buyer_list.html
{% extends 'base.html' %}
{% block title %}Clients list{% endblock %}
{% block content %}

<div class="align-items-center justify-content-center flex">
    <div class="text-center frosty-container mx-auto my-3">
    <a href="{% url 'billing:add_buyer' %}" class="btn text-info mb-3">Add Client</a>
    <h3>Your Clients</h3>
    
    <hr class="w-25 mx-auto">
    {% for buyer in object_list %}
        <p>{{ buyer.name }} <a href="{% url 'billing:update_buyer' buyer.pk %}" class="btn btn-outline-info">Edit</a> <a href="{% url 'billing:delete_buyer' buyer.pk %}" class="btn btn-danger">Delete</a></p>
        <hr class="w-50 mx-auto">
    {% endfor %}

    </div>
</div>

{% endblock %}

invoices/billing/templates/billing/invoice_confirm_delete.html
{% extends 'base.html' %}
{% block title %}Delete Invoice{% endblock %}
{% block content %}

<h3 class="my-3">Are you sure you want to delete Invoice Nr: {{ object.number }} for client: {{ object.buyer.name }} ?</h3>
<form method='post'>
    {% csrf_token %}
    <button type='submit' class='btn btn-danger'>Yes, DELETE</button>
    <a href='{% url "billing:detail_invoice" object.pk %}' class='btn btn-outline-primary'>Cancel</a>
</form>

{% endblock %}

invoices/billing/templates/billing/invoice_detail.html
{% extends 'base.html' %}
{% block title %}Invoice {{ invoice.number }}{% endblock %}
{% block content %}

<a href="{% url 'billing:invoice_pdf' invoice.pk %}" class="btn btn-outline-primary">PDF</a>
<a href="{% url 'billing:update_invoice' invoice.pk %}" class="btn btn-outline-primary">Update Header</a> 
<a href="{% url 'billing:delete_invoice' invoice.pk %}" class="btn btn-danger">DELETE Invoice</a>
<hr/>
<h3 clas='my-3'>Invoice Series: {{ invoice.series }}, No.: {{ invoice.number }}</h3>
<p>Buyer: {{ invoice.buyer }}</p>
<p>Issue date: {{ invoice.issue_date }}</p>
<p>To be paid until: {{ invoice.due_date }}</p>
<p>Vat included: {% if invoice.include_vat %}Yes{% else %}No{% endif %}


<hr>
    <a href="{% url 'billing:create_item' invoice.pk %}" class="btn btn-outline-primary mb-3">Add item</a>
    {% if invoice.items %}
    <table class="table table-striped table-responsive align-middle">
        <thead>
            <tr>
                <th style="width: 10%"></th>
                <th style="width: 40%">Description</th>
                <th style="width: 10%">Quantity</th>
                <th style="width: 10%">Units</th>
                <th style="width: 15%">Price</th>
                <th style="width: 15%">Total</th>
            </tr>
        </thead>
        <tbody>
        {% for item in invoice.items.all %}
        <tr>
            <td><a href={% url 'billing:update_item' item.pk %}>Edit</a> / 
            <a href={% url 'billing:delete_item' item.pk %} class="text-danger">Delete</a></td>
            <td>{{ item.description }}</td>
            <td>{{ item.qty }}</td>
            <td>{{ item.units }}</td>
            <td>{{ item.price }} eur</td>
            <td>{{ item.line_total }} eur</td>
        </tr>
        {% endfor %}
        {% if invoice.include_vat %}
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td><strong>Subtotal:</strong></td>
            <td><strong>{{ invoice.subtotal }} eur</strong></td>
        </tr>
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td><strong>VAT:</strong></td>
            <td><strong>{{ invoice.vat_amount }} eur</strong></td>
        </tr>
        {% endif %}
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td><strong>Invoice total:</strong></td>
            <td><strong>{{ invoice.total }} eur</strong></td>
        </tr>
        </tbody>
    </table>
    {% else %}
    <p>No items yet</p>
    {% endif %}

{% endblock %}

invoices/billing/templates/billing/invoice_form.html
{% extends 'base.html' %}
{% block title %}{{ var }} invoice{% endblock %}
{% block content %}
{% load crispy_forms_tags %}
<div class="align-items-center justify-content-center flex">
    <div class="text-start frosty-container mx-auto my-3">
        <h3>{{ var }} invoice</h3>
        <form method='post'>
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-outline-info">Confirm invoice {{ var }}</button>
        </form>
    </div>
</div>     

{% endblock %}

invoices/billing/templates/billing/invoice_list.html
{% extends 'base.html' %}
{% block title %}List Invoices{% endblock %}
{% block content %}

<div class="align-items-center justify-content-center flex">
    <div class="text-center frosty-container mx-auto my-3">
        
        <a href="{% url 'billing:create_invoice' %}" class="btn text-info mb-3">Create New Invoice</a>
        <h3>Your invoices</h3>
        <hr class="w-25 mx-auto">
        {% for invoice in object_list %}
            <p>Client: "<strong><i>{{ invoice.buyer.name }}</i></strong>"  |  No.: {{ invoice.number }}  |  Total: {{ invoice.total }}  <a href="{% url 'billing:detail_invoice' invoice.pk %}" class="btn btn-outline-info">Details..</a> </p>
            <hr class="w-50 mx-auto">
        {% endfor %}
    </div>
</div>
{% endblock %}

invoices/billing/templates/billing/invoiceitem_confirm_delete.html
{% extends 'base.html' %}
{% block title %}Delete Invoice Item{% endblock %}
{% block content %}

<h3 class="my-3">Are you sure you want to delete {{ object.name }} </h3>
<p>For Invoice Nr: {{ object.number }} for client: {{ object.buyer.name }} ?</p>
<form method='post'>
    {% csrf_token %}
    <button type='submit' class='btn btn-danger'>Yes, DELETE</button>
    <a href='{% url "billing:detail_invoice" object.invoice.pk %}' class='btn btn-outline-primary'>Cancel</a>
</form>

{% endblock %}

invoices/billing/templates/billing/invoiceitem_form.html
{% extends 'base.html' %}
{% block title %}{{ var }} invoice item{% endblock %}
{% block content %}
{% load crispy_forms_tags %}

<h3>{{ var }} invoice item</h3>
<form method='post'>
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-outline-primary">{{ var }} item</button>
</form>

{% endblock %}

invoices/billing/templates/billing/pdf_template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Invoice</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        @page {
            size: A4;
            margin: 2cm;
        }

        body {
            font-family: sans-serif;
        }

        .invoice-box {
            width: 100%;
        }

        div.header {
            text-align: center;
            font-size: 24px;
            margin-bottom: 5px;
        }

        p.header {
            text-align: center;
            font-size: 14px;
            margin-bottom: 5px;
        }

        p {
            margin: 0px;
            font-size: 14px;
        }

        h5 {
            font-size: 14px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            font-size: 12px;
        }

        table th, table td {
            border: 1px solid #ddd;
            padding: 8px;
        }

        table th {
            background-color: #f2f2f2;
        }
    </style>
</head>
<body>

    <div class="invoice-box">
        <div class="header">INVOICE</div>
        <div class="header">Series: <strong>{{ invoice.series }}</strong>, No.: <strong>{{ invoice.number }}</strong></div>
        <p class="header">Date: <strong>{{ invoice.issue_date|date:"Y-m-d" }}</strong></p>
        <p class="header mb-3">To be paid until: <strong>{{ invoice.due_date|date:"Y-m-d" }}</strong></p>

        <div class="row">
            <div class="col-6">
                <p><strong>Seller: </strong></p>
                <p class="mb-2"><i>{{ invoice.user.profile.name }}</i></p>
                {% with profile=invoice.user.profile %}
                    <p><strong>Address:</strong> {{ profile.address }}</p>
                    {% if invoice.user.is_company and profile.company_code %}
                        <p><strong>Company code:</strong> {{ profile.company_code }}</p>
                    {% elif not invoice.user.is_company and profile.individual_code %}
                        <p><strong>Individual code:</strong> {{ profile.individual_code }}</p>
                    {% endif %}
                    {% if profile.vat_code %}
                        <p class="mb-2"><strong>VAT code:</strong> {{ profile.vat_code }}</p>
                    {% endif %}
                    
                {% endwith %}
                {% with bank=invoice.user.bank %}
                    <p><strong>IBAN:</strong> {{ bank.iban }}</p>
                    {% if bank.bank_name %}<p><strong>Bank name:</strong> {{ bank.bank_name }}</p>{% endif %}
                    {% if bank.swift %}<p><strong>SWIFT:</strong> {{ bank.swift }}</p>{% endif %}
                {% endwith %}
            </div>
            <div class="col-1"></div>
            <div class="col-5">
                <p><strong>Buyer: </strong></p>
                <p class="mb-2"><i>{{ invoice.buyer.name }}</i></p>
                {% if invoice.buyer.address %}<p><strong>Address:</strong> {{ invoice.buyer.address }}</p>{% endif %}
                <p><strong>Pers/Company code:</strong> {{ invoice.buyer.code }}</p>
                {% if invoice.buyer.vat_code %}
                        <p class="mb-2"><strong>VAT code:</strong> {{ invoice.buyer.vat_code }}</p>
                    {% endif %}
            </div>
        </div>
    {% if invoice.items %}
    <table class="table align-middle mt-5">
        <thead>
            <tr>
                <th style="with: 5%">#</th>
                <th style="width: 40%">Description</th>
                <th style="width: 10%">Quantity</th>
                <th style="width: 10%">Units</th>
                <th style="width: 15%">Price (eur)</th>
                <th style="width: 20%">Total (eur)</th>
            </tr>
        </thead>
        <tbody>
        {% for item in invoice.items.all %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ item.description }}</td>
            <td>{{ item.qty }}</td>
            <td>{{ item.units }}</td>
            <td>{{ item.price }}</td>
            <td>{{ item.line_total }}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    {% if invoice.include_vat %}
    <h5 class="text-end">Subtotal: <strong>{{ invoice.subtotal }} eur</strong></h5>
    <h5 class="text-end">VAT total: <strong>{{ invoice.vat_amount }} eur</strong></h5>
    <h5 class="text-end">Total sum: <strong>{{ invoice.total }} eur</strong></h5>
    {% else %}
    <h5 class="text-end">Total sum: <strong>{{ invoice.total }} eur</strong></h5>
    {% endif %}
    <p class="mt-3"><strong>Total in words:</strong> {{ amount_in_words|capfirst }}</p>
    </div>
    {% else %}
    No items added!
    {% endif %}

    <div class="fixed-bottom">
        {% with profile=invoice.user.profile %}
            {% if profile.phone %}<p>Phone: {{ profile.phone }}</p>{% endif %}
            {% if profile.email %}<p>Email: {{ profile.email }}</p>{% endif %}
        {% endwith %}
    <div>
</body>